import { useState, useEffect } from 'react';

const TermsOfUse = () => {
  const [terms, setTerms] = useState<string>('');

  useEffect(() => {
    let termsURL = `${process.env.PUBLIC_URL}/terms_of_use.html`;
    fetch(termsURL)
      .then(response => {
        return response.text()
      })
      .then(text => {
        setTerms(text)
      })
  }, [terms]);

  return (
    <div>
      <h1 id="termsofusesoundrecorder">Terms of Use Sound Recorder</h1>
<p>Last revised on 11-11-2022</p>
<h2 id="thegist">The Gist</h2>
<p>Secret Source Technology produces the Sound Recorder web application, which we hope you use. If you use it, please use it responsibly.</p>
<p>For paid accounts, you'll be charged on a monthly basis. You can cancel anytime, but there are no refunds.</p>
<p>The Terms of Sound Recorder, Sound Recorder itself, and our prices can change at any time. We'll warn you 30 days in advance of any price changes. We'll try to warn you about major changes to the Terms of Sound Recorder or Sound Recorder, but we make no guarantees.</p>
<p>That's the basic idea, but You must read through the entire Terms of Sound Recorder below and agree with all the details before You use this web application.</p>
<h2 id="youragreementwithsecretsourcetechnology">Your Agreement with Secret Source Technology</h2>
<p>Your use of the Secret Source Technology Sound Recorder is governed by this agreement (the "Terms"). "Secret Source Technology" means <a href="https://secret-source.eu">Secret Source Technology SLU</a>. The "Sound Recorder" means Sound Recorders Secret Source Technology makes available including our web sites ([https://secret-source.eu]), our blog, our API, and any other software, sites, and services offered by Secret Source Technology in connection to any of those. "Content" means all content generated by Secret Source Technology on your behalf (including metric data).</p>
<p>In order to use Sound Recorder, You (the "Customer", "You", or "Your") must first agree to the Terms. You understand and agree that Secret Source Technology will treat Your use of Sound Recorder as acceptance of the Terms from that point onwards.</p>
<p>Secret Source Technology may make changes to the Terms from time to time. You may reject the changes by terminating Your account or closing the application if no account is associted with your use of Sound Recorder. You understand and agree that if You use Sound Recorder after the date on which the Terms have changed, Secret Source Technology will treat Your use as acceptance of the updated Terms.</p>
<p>If you have any question about the Terms, please contact us at info@secret-source.eu.</p>
<h2 id="youraccount">Your Account</h2>
<ul>
<li>You may not use Sound Recorder if You are a person barred from receiving Sound Recorder under the laws of the United States or other countries, including the country in which You are resident or from which You use Sound Recorder.</li>
<li>You must be a human. Accounts created by automated methods are not permitted.</li>
</ul>
<h2 id="useofsoundrecorder">Use of Sound Recorder</h2>
<ul>
<li>You must provide accurate and complete registration information any time You register to use Sound Recorder.</li>
<li>You are responsible for the security of Your passwords and for any use of Your account.</li>
<li>Your use of Sound Recorder must comply with all applicable laws, regulations and ordinances.</li>
<li>You agree to not engage in any activity that interferes with or disrupts Sound Recorder.</li>
<li>Secret Source Technology reserves the right to enforce quotas and usage limits (to any resources, including the API) at its sole discretion, with or without notice, which may result in Secret Source Technology disabling or throttling your usage of Sound Recorder for any amount of time.</li>
<li>You may not allow multiple people to use the same account or otherwise access Sound Recorder in a manner intended to avoid incurring fees.</li>
</ul>
<h2 id="soundrecorderpoliciesandprivacy">Sound Recorder Policies and Privacy</h2>
<p>Sound Recorder shall be subject to the privacy policy for Sound Recorder (below). You agree to the use of Your data in accordance with Secret Source Technology's privacy policies.</p>
<h2 id="feesforuseofsoundrecorder">Fees for Use of Sound Recorder</h2>
<ul>
<li>Sound Recorder may be provided to You without charge up with certain limits or for a certain "trial" period of time.</li>
<li>Usage over this limit (or after the "trial" period) requires Your purchase of additional resources or services.</li>
<li>For all purchased resources and services, we will charge Your credit card on a monthly basis.</li>
<li>Payments are non-refundable. There will be no refunds or credits for partial months of service, upgrade/downgrade refunds, or refunds for months unused with an open account.</li>
<li>Charges are solely based on Secret Source Technology's measurements of Your use of Sound Recorder, unless otherwise agreed to in writing.</li>
<li>All fees are exclusive of all taxes, levies, or duties imposed by taxing authorities, and You shall be responsible for payment of all such taxes, levies, or duties.</li>
<li>You acknowledge and agree that any credit card and related billing and payment information that You provide to Secret Source Technology may be shared by Secret Source Technology with companies who work on Secret Source Technology's behalf, such as payment processors and/or credit agencies, solely for the purposes of checking credit, effecting payment to Secret Source Technology and servicing Your account.</li>
<li>Secret Source Technology may change its fees and payment policies for Sound Recorder by notifying You at least thirty (30) days before the beginning of the billing cycle in which such change will take effect.</li>
</ul>
<h2 id="cancellationandtermination">Cancellation and Termination</h2>
<ul>
<li>You must cancel Your account via [URL]. An email or phone request to cancel Your account is not considered cancellation.</li>
<li>You will not receive any refunds if You cancel Your account.</li>
<li>If You cancel Sound Recorder before the end of Your current paid up month, Your cancellation will take effect immediately and You will not be charged again.</li>
<li>All of Customer Recordings and Content will, within a reasonable amount of time to be determined solely by Secret Source Technology, be deleted from Sound Recorder upon cancellation.</li>
<li>You agree that Secret Source Technology, in its sole discretion and for any or no reason, may terminate or suspend Your account. You agree that any termination of Your access to Sound Recorder may be without prior notice, and You agree that Secret Source Technology will not be liable to You or any third party for such termination.</li>
</ul>
<h3 id="customerrecordings">Customer Recordings</h3>
<ul>
<li>Secret Source Technology claims no ownership or control over any Customer Recordings. You retain copyright and any other rights You already hold in the Customer Recordings and You are responsible for protecting those rights, as appropriate.</li>
<li>You agree to assume full responsibility for configuring Sound Recorder to allow appropriate access to any Customer Recordings provided to Sound Recorder.</li>
<li>You understand that public recordings display Customer Recordings to any party on the Internet, including search engines and web spiders.</li>
<li>You understand that private recordings will display Customer Recordings to You and any collaborators that you designate for that project.</li>
<li>You retain sole responsibility for any collaborators or third-party services that you allow to view Customer Recordings and entrust them at your own risk.</li>
<li>Secret Source Technology is not responsible if you fail to configure, or misconfigure, your recordings and inadvertently allow unauthorized parties view any Customer Recordings.</li>
</ul>
<h2 id="ideasandfeedback">Ideas and Feedback</h2>
<p>You may choose to or we may invite You to submit comments or ideas about Sound Recorder, including but not limited to ideas about improving Sound Recorder or our products ("Ideas"). By submitting any Idea, You agree that Your disclosure is unsolicited and without restriction and will not place Secret Source Technology under any fiduciary or other obligation, and that we are free to use the Idea without any additional compensation to You, and/or to disclose the Idea on a non-confidential basis or otherwise to anyone.</p>
<h2 id="modificationofsoundrecorder">Modification of Sound Recorder</h2>
<ul>
<li>You acknowledge and agree that Sound Recorder may change from time to time without prior notice to You.</li>
<li>Changes include, without limitation, changes to fee and payment policies, security patches, added or removed functionality, and other enhancements or restrictions.</li>
<li>Secret Source Technology shall not be liable to you or to any third party for any modification, price change, suspension or discontinuance of Sound Recorder.</li>
</ul>
<h2 id="externalresources">External Resources</h2>
<p>Sound Recorder may include hyperlinks to other web sites or content or resources or email content. You acknowledge and agree that Secret Source Technology is not responsible for the availability of any such external sites or resources, and does not endorse any advertising, products or other materials on or available from such web sites or resources.</p>
<h3 id="licensefromsecretsourcetechnologyandrestrictions">License from Secret Source Technology and Restrictions</h3>
<p>Secret Source Technology gives You a personal, worldwide, royalty-free, non-assignable and non-exclusive license to use the software provided to You by Secret Source Technology as part of Sound Recorder as provided to You by Secret Source Technology. This license is for the sole purpose of enabling You to use and enjoy the benefit of Sound Recorder as provided by Secret Source Technology, in the manner permitted by the Terms.</p>
<p>You may not (and You may not permit anyone else to): (a) copy, modify, create a derivative work of, reverse engineer, decompile or otherwise attempt to extract the source code of Sound Recorder or any part thereof, unless this is expressly permitted or required by law, or unless You have been specifically told that You may do so by Secret Source Technology, in writing (e.g., through an open source software license); or (b) attempt to disable or circumvent any security mechanisms used by Sound Recorder. To be clear, this product is open source and the source code is available for download. You may not use Sound Recorder in any way that is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.</p>
<p>Open source software licenses for components of Sound Recorder released under an open source license constitute separate written agreements. To the limited extent that the open source software licenses expressly supersede these Terms, the open source licenses govern Your agreement with Secret Source Technology for the use of the components of Sound Recorder released under an open source license.</p>
<h2 id="exclusionofwarranties">Exclusion of warranties</h2>
<ul>
<li>You expressly understand and agree that your use of Sound Recorder is at your sole risk and that Sound Recorder is provided "as is" and "as available.".</li>
<li>You agree that Secret Source Technology has no responsibility or liability for the deletion or failure to store any Content and other communications maintained or transmitted through use of Sound Recorder. You further acknowledge that You are solely responsible for securing and backing up Customer Recordings.</li>
<li>Secret Source Technology does not warrant to you that: (a) your use of Sound Recorder will meet your requirements, (b) your use of Sound Recorder will be uninterrupted, timely, secure or free from error, (c) the results or data provided by Sound Recorder will be accurate, (d) the quality of Sound Recorder will meet your expectations and (e) any errors in Sound Recorder will be fixed.</li>
</ul>
<h2 id="limitationofliability">Limitation of liability</h2>
<p>You expressly understand and agree that Secret Source Technology, its subsidiaries and affiliates, and its licensors shall not be liable to you for any direct, indirect, incidental, special consequential or exemplary damages which may be incurred by you, however caused and under any theory of liability. This shall include, but not be limited to, any loss of profit (whether incurred directly or indirectly), any loss of goodwill or business reputation, any loss of data suffered, cost of procurement of substitute goods or services, or other intangible loss (whether or not Secret Source Technology has been advised of or should have been aware of the possibility of any such losses arising).</p>
<h2 id="indemnification">Indemnification</h2>
<p>You agree to hold harmless and indemnify Secret Source Technology, and its subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers or partners (collectively "Secret Source Technology and Partners") from and against any third party claim arising from or in any way related to (a) Your breach of the Terms, (b) Your use of Sound Recorder, (c) Your violation of applicable laws, rules or regulations in connection with Sound Recorder, or (d) Your Customer Recordings, including any liability or expense arising from all claims, losses, damages (actual and consequential), suits, judgments, litigation costs and attorneys' fees, of every kind and nature. In such a case, Secret Source Technology will provide You with written notice of such claim, suit or action.</p>
<h2 id="generallegalterms">General Legal Terms</h2>
<p>The Terms constitute the whole legal agreement between You and Secret Source Technology and govern Your use of Sound Recorder and completely replace any prior agreements between You and Secret Source Technology in relation to Sound Recorder.</p>
<p>You agree that if Secret Source Technology does not exercise or enforce any legal right or remedy which is contained in the Terms (or which Secret Source Technology has the benefit of under any applicable law), this will not be taken to be a formal waiver of Secret Source Technology's rights and that those rights or remedies will still be available to Secret Source Technology.</p>
<p>Secret Source Technology shall not be liable for failing or delaying performance of its obligations resulting from any condition beyond its reasonable control, including but not limited to, governmental action, acts of terrorism, earthquake, fire, flood or other acts of God, labor conditions, power failures, and Internet disturbances.</p>
<h2 id="privacypolicy">Privacy Policy</h2>
<p>Secret Source Technology will make every effort to protect data you transfer to us according to the Terms of Use above. However, we make zero warranty or guarantee over their safe return in the event of unauthorized access. As of this writing, this application does not track user activity in any way with the exception of potential cookies sent by hosting services. Sound Recorder and Secret Source Technology do not make any use of this data whatsoever. We do not even look at it if it exists!</p>
    </div>
  )
}

export default TermsOfUse
