/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { Queue } from 'workbox-background-sync';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith('/_')) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && (url.pathname.endsWith('.png') || url.pathname.endsWith('.jpg') || url.pathname.endsWith('.webp')),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Background sync queue for Freesound uploads
// Uses HttpOnly cookies for authentication - no need to read tokens from IndexedDB
const uploadQueue = new Queue('freesound-uploads', {
  maxRetentionTime: 24 * 60, // 24 hours in minutes
  onSync: async ({ queue }) => {
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        // Replay the request - cookies are automatically included
        const response = await fetch(entry.request.clone(), {
          credentials: 'include',
        });

        if (!response.ok) {
          if (response.status === 401) {
            // Session expired, re-queue for retry after user re-authenticates
            await queue.unshiftRequest(entry);
            console.log('[SW] Session expired, will retry after re-authentication');
            return;
          }
          throw new Error(`Upload failed: ${response.status}`);
        }

        // Notify main thread of success
        const clients = await self.clients.matchAll();
        const result = await response.json();
        clients.forEach(client => {
          client.postMessage({
            type: 'UPLOAD_COMPLETE',
            recordingId: entry.metadata?.recordingId,
            freesoundId: result.id
          });
        });

        console.log('[SW] Upload completed successfully:', result.id);

      } catch (error) {
        console.error('[SW] Upload failed, re-queuing:', error);
        // Network error - re-queue for retry
        await queue.unshiftRequest(entry);
        throw error; // Let workbox handle retry timing
      }
    }
  }
});

// Log all fetch events for debugging
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (url.pathname.includes('/api/')) {
    console.log('[SW] Fetch intercepted:', event.request.method, url.pathname);
  }
});

// Register route to intercept upload requests to our proxy
// Uploads now go through the proxy: /api/sounds/upload/
registerRoute(
  ({ url, request }) => {
    const matches = url.pathname.includes('/api/sounds/upload/') && request.method === 'POST';
    console.log('[SW] Route check:', url.pathname, request.method, 'matches:', matches);
    return matches;
  },
  async ({ request }) => {
    console.log('[SW] Upload route handler called');
    try {
      const response = await fetch(request.clone(), {
        credentials: 'include',
      });
      console.log('[SW] Upload response:', response.status);
      if (response.ok) return response;

      // Non-OK response - queue for background sync retry
      const recordingId = request.headers.get('X-Recording-Id');
      await uploadQueue.pushRequest({
        request: request.clone(),
        metadata: { recordingId: recordingId ? parseInt(recordingId, 10) : undefined }
      });

      console.log('[SW] Upload failed, queued for background sync');
      return response;
    } catch (error) {
      console.log('[SW] Upload network error, queuing...');
      // Network failure - queue for background sync
      const recordingId = request.headers.get('X-Recording-Id');
      await uploadQueue.pushRequest({
        request: request.clone(),
        metadata: { recordingId: recordingId ? parseInt(recordingId, 10) : undefined }
      });

      console.log('[SW] Network error, queued for background sync');
      throw error;
    }
  },
  'POST'
);

// Any other custom service worker logic can go here.
